### ISSUE TITLE
开发者大大你好，我在您的程序中遇到了一个这样问题。当在使用鲁迅说命名时，出现了下面的报错

### ISSUE THREAD

**Issue by chenanmo** [NothAmor/nonebot2_luxun_says#1]
05-12 23:05:18 [INFO] nonebot | Event will be handled by <Matcher from luxun_says, type=message, priority=1, temp=False>
05-12 23:05:18 [DEBUG] nonebot | Running matcher <Matcher from luxun_says, type=message, priority=1, temp=False>
05-12 23:05:18 [INFO] nonebot | Matcher <Matcher from luxun_says, type=message, priority=1, temp=False> running complete
05-12 23:05:18 [ERROR] nonebot | Running matcher <Matcher from luxun_says, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.pyenv/versions/3.9.0b5/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/.pyenv/versions/3.9.0b5/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/root/.pyenv/versions/3.9.0b5/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/.pyenv/versions/3.9.0b5/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/nonebot/message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/nonebot/message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/nonebot/matcher.py", line 544, in run
    await handler(self, bot, event, state_)
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/nonebot/handler.py", line 81, in __call__
    await self.func(
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/nonebot/matcher.py", line 427, in wrapper
    await func_handler(matcher, bot, event, state)
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/nonebot/handler.py", line 81, in __call__
    await self.func(
  File "src/plugins/luxun_says/__init__.py", line 35, in handle_event
    await process_pic(content, filename)
  File "src/plugins/luxun_says/__init__.py", line 48, in process_pic
    font = ImageFont.truetype(font_path, 37)
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/PIL/ImageFont.py", line 853, in truetype
    return freetype(font)
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/PIL/ImageFont.py", line 850, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/qqbot/nonebot2/nonetbot_venv/lib/python3.9/site-packages/PIL/ImageFont.py", line 209, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by NothAmor** [comment]
不好意思, 我才看到这个issue, 看样子应该是Python试图打开字体文件时遇到了问题, 请问你的nonebot运行在什么操作系统中?
如果是Linux操作系统的话, 可以尝试将字体安装到系统中来解决, 尝试以下步骤:
```
首先cd到插件luxun_says目录
1. cp 字体名字 /usr/share/fonts/
2. cd /usr/share/fonts/
3. mkfontscale
4. mkfontdir
```
最后，fc-list查看是否存在, 如果存在的话, 再尝试调用一次本插件

**Comment by chenanmo** [comment]
非常抱歉没有提供完整的信息，下次将会注意，已安装您的方法进行了字体安装，已经解决了该问题，非常感谢
